import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ThemeProvider from "@/providers/ThemeProvider";
import { WalletProvider } from "@/providers/WalletProvider";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${inter.className} bg-purple-default`}>
      {/*{children}*/}
      <NextIntlClientProvider messages={messages}>
        <WalletProvider>
          <ReactQueryProvider>
            <ThemeProvider>
              <AntdRegistry>{children}</AntdRegistry>
            </ThemeProvider>
          </ReactQueryProvider>
        </WalletProvider>
      </NextIntlClientProvider>

      </body>
    </html>
  );
}
