import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ThemeProvider from '@/providers/ThemeProvider';
import { WalletProvider } from '@/providers/WalletProvider';
import { ReactQueryProvider } from '@/providers/ReactQueryProvider';
import NextThemeProvider from '@/providers/NextThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-purple-default dark:bg-black text-black dark:text-white`}>
        {/*{children}*/}
        <WalletProvider>
          <ReactQueryProvider>
            <NextThemeProvider>
              <ThemeProvider>
                <AntdRegistry>{children}</AntdRegistry>
              </ThemeProvider>
            </NextThemeProvider>
          </ReactQueryProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
