import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import ThemeProvider from "@/providers/ThemeProvider";
import {WalletProvider} from "@/providers/WalletProvider";
import {ReactQueryProvider} from "@/providers/ReactQueryProvider";
import TranslationsProvider from "@/providers/TranslationProvider";
import initTranslations from "@/app/i18n";
import {defaultNS, fallbackLng, namespaces} from "@/i18n";
import i18nConfig from "../../../i18nconfig";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: {lng}, }: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  const {resources} = await initTranslations(lng || fallbackLng, namespaces);
  return (
    <html lang={lng || fallbackLng}>
    <body className={`${inter.className} bg-purple-default`}>
    {/*{children}*/}
    <ReactQueryProvider>
      <WalletProvider>
        <TranslationsProvider namespaces={[defaultNS]} locale={lng} resources={resources}>
          <ThemeProvider>
            <AntdRegistry>{children}</AntdRegistry>
          </ThemeProvider>
        </TranslationsProvider>
      </WalletProvider>
    </ReactQueryProvider>
    </body>
    </html>
  );
}

export function generateStaticParams() {
  return i18nConfig.locales.map((lng) => ({ lng }));
}