import type { Metadata} from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {locales} from "@/i18n/config";
import {Props} from "@/types/Layout";
import Provider from "./provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// 生成多语言静态页面
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export default function RootLayout({
  children,
  params:{locale},
}: Readonly<Props>) {
  return (
    <html lang={locale}>
      <body className={`${inter.className} bg-purple-default`}>
        <Provider params={{locale}}>{children}</Provider>
      </body>
    </html>
  );
}
